### ISSUE TITLE
Data and run issues

### ISSUE THREAD

**Issue by wanghuijia326** [JRC1995/BERT-Disaster-Classification-Capsule-Routing#1]
1、Excuse me, where can I download those datasets?
2、If data set is available, can it theoretically work? Does the program need other modifications?

**Comment by wanghuijia326** [comment]
3、Is this suitable for binary classification problem (0,1 label)？

**Comment by JRC1995** [comment]
1. I just updated the readme file with all the details here: https://github.com/JRC1995/BERT-Disaster-Classification-Capsule-Routing/blob/master/README.md

2. Yes it should work if the data set is properly processed and set up and pre-trained BERT model is downloaded and [saved locally](https://github.com/JRC1995/BERT-Disaster-Classification-Capsule-Routing#saving-multilingual-bert). Mainly, you have to make sure that these files are available in this format: https://github.com/JRC1995/BERT-Disaster-Classification-Capsule-Routing#using-your-own-data-or-your-own-data-processing-code. It doesn't matter how you prepare the files (you can use the instructions [here](https://github.com/JRC1995/BERT-Disaster-Classification-Capsule-Routing#data-processing) or come up with your own ways). 

3. I used a multi-task setup with both binary-classification and multi-class classification. See the [project report and the slides](https://github.com/JRC1995/BERT-Disaster-Classification-Capsule-Routing#disaster-related-tweet-classification-with-bert) for details. So currently the codes expect both tasks. So it's not exactly suitable at the moment for **_just_** binary classification. 
However the minimal modification that you can do to use this solely for binary classification is to use 'dummy' multi-class data (you can treat the binary classes themselves as multi-class labels) and set gamma1 as 1.0 and gamma2 as 0 in this [code](https://github.com/JRC1995/BERT-Disaster-Classification-Capsule-Routing/blob/master/Classification/modules/utils.py) -  this will ensure that the loss from the "multi-class classifier" is completely ignored and the model will be effectively trained for binary classification in a single-task-training-manner. It would not be the most efficient setup but the one you can establish with the least amount of modification (that I can think of at the moment).

**Comment by wanghuijia326** [comment]
Thanks!
But now I have another question：
When I run save_pre_trained_locally.py,always fail to connect.
Downloading:   0%|          | 3.22M/714M [13:09<10640:39:53, 18.6B/s]Traceback (most recent call last):
ConnectionResetError: [Errno 104] Connection reset by peer
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')"

Can you send me a link to download the pretrained-bert webpage directly?

**Comment by JRC1995** [comment]
The downloading is done through HuggingFace's library: https://github.com/huggingface/transformers
There is nothing much I can do about it. I am not sure if they have the download links easily available in somewhere public but you can look for them. But I can upload and share the weights through my drive: https://drive.google.com/drive/folders/1YNjxyCEV98_XU91wgsJIweIjjTublq48?usp=sharing (I will probably remove it again from my drive a few days later. So download it now if possible)

**Comment by JRC1995** [comment]
Here's the official download like: https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-multilingual-cased-pytorch_model.bin
