### ISSUE TITLE
Question about capsule_fusion

### ISSUE THREAD

**Issue by ruizewang** [JRC1995/BERT-Disaster-Classification-Capsule-Routing#3]
Hello,
Thanks for your great work~ 
Here I have one question in " https://github.com/JRC1995/BERT-Disaster-Classification-Capsule-Routing/blob/master/Classification/model/layers/capsule_net.py":
What is the meaning of  "D, n_in, n_out, in_dim, out_dim, depth_encoding"?

`class capsule_fusion(nn.Module):
    def __init__(self, D, n_in, n_out, in_dim, out_dim, depth_encoding=False):`

**Comment by JRC1995** [comment]
D is the model (hidden state embedding) dimension 
n_in is the number of input capsules (it is expected n_in is 1 for variable capsules, or equal to the capsule size in the incoming input shape. The input is expected to be of batch x num_capsules x D shape. num_capsules == n_in if n_in !=1. You can also set n_in as 1 if there is only one capsule )
n_out is the number of output capsules
in_dim is the dimensions for input capsules .
out_dim is the dimensions for output capsules
depth_encoding is usually for layer fusion --- essentially it adds a special "depth embedding" (different embedding for different layers, to give some extra signal of which depth of layer it is).

**Comment by ruizewang** [comment]
> D is the model (hidden state embedding) dimension
> n_in is the number of input capsules (it is expected n_in is 1 for variable capsules, or equal to the capsule size in the incoming input shape. The input is expected to be of batch x num_capsules x D shape. num_capsules == n_in if n_in !=1. You can also set n_in as 1 if there is only one capsule )
> n_out is the number of output capsules
> in_dim is the dimensions for input capsules .
> out_dim is the dimensions for output capsules
> depth_encoding is usually for layer fusion --- essentially it adds a special "depth embedding" (different embedding for different layers, to give some extra signal of which depth of layer it is).

Thanks for your quick and detailed reply : )
